jobs:
 -
  kernel_include_regex: '^aiter::f8gemm_bf16_mxfp8fp4_ABpreShuffle_256x256_4x4_ps$'
  kernel_exclude_regex:
  kernel_iteration_range: "[1]"
  output_file: out
  output_directory: my_code/.get_isa_runner_att_f8gemm_bf16_mxfp8fp4_ABpreShuffle_256x256_4x4_ps.asm.b8-3.att_1578/thread_trace/simd1/kernel/rpf_v3
  output_format: [csv]
  truncate_kernels: false
  sys_trace: false
  advanced_thread_trace: true
  att_target_cu: 1
  att_shader_engine_mask: "0xf"
  att_simd_select: "1"
  att_buffer_size: "0x10000000"
  att_library_path: ["/data/yanguahe/code/wk_sp1/decoder_new"]
