jobs:
 -
  kernel_include_regex: '^moe_gemm1_mxfp4_ABpreShuffle_256x256_4x4_batch_ps_act1$'
  kernel_exclude_regex:
  kernel_iteration_range: "[1]"
  output_file: out
  output_directory: my_code/moe_gemm1_act1_optimized/history_runs/heliosr-1b114-d01-3_20260912T154121Z_att/att/.get_isa_runner_att_candidate_40703/thread_trace/kernel/rpf_v3
  output_format: [csv]
  truncate_kernels: false
  sys_trace: false
  advanced_thread_trace: true
  att_target_cu: 1
  att_shader_engine_mask: "0xf"
  att_simd_select: "3"
  att_buffer_size: "0x10000000"
  att_library_path: ["/data/yanguahe/code/wk_sp1/decoder_new"]
