jobs:
 -
  kernel_include_regex: '^a8w4_tdm_fp4_t64x256x256_w1x4_b2_K3072_e96$'
  kernel_exclude_regex:
  kernel_iteration_range: "[1]"
  output_file: out
  output_directory: my_code/.get_isa_runner_att_gemm2_a4w4.4sm.b8-3.att_9362/thread_trace/simd3/kernel/rpf_v3
  output_format: [csv]
  truncate_kernels: false
  sys_trace: false
  advanced_thread_trace: true
  att_target_cu: 1
  att_shader_engine_mask: "0xf"
  att_simd_select: "3"
  att_buffer_size: "0x10000000"
  att_library_path: ["/data/yanguahe/code/wk_sp1/decoder_new"]
